server:
  port: 8080
  servlet:
    context-path: /mms
# Spring 配置
spring:
  application:
    name: mms
    # 数据库连接
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1qaz!QAZ
    url: jdbc:mysql://localhost:3306/mms?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=Asia/Shanghai&useSSL=false
    database-name: mms
  # flyway
  flyway:
    locations:
      baselineOnMigrate: true
      classpath: db/migration
      url: jdbc:mysql://localhost:3306/mms?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=Asia/Shanghai&useSSL=false
      schemas: mms_flyway
      user: root
      password: 1qaz!QAZ
      enabled: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    static-path-pattern: /static/**
  freemarker:
    cache: false
    charset: UTF-8
    content-type: text/html
    suffix: .ftl
    check-template-location: true
    template-loader-path: classpath:/templates
    expose-request-attributes: true
    expose-session-attributes: true
    expose-spring-macro-helpers: false
    request-context-attribute: rc
    settings:
      number_format: 0
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**
    freemarker:
      cache: false    #页面不加载缓存，修改即时生效
## mybatis-plus 配置 typeAliasesPackage mapperLocations
mybatis-plus:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.sunh.mms.entity
#  configuration:
#    ## 日志
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl